# Generated by Django 3.1.5 on 2021-02-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='zip_code',
        ),
    ]
