# Generated by Django 3.1.5 on 2021-02-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number',
        ),
    ]
